name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Project
      run: ./gradlew assemble

    - name: Run Tests
      run: ./gradlew test

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
       name: unit_test_report
       path: app/build/reports/tests/testDebugUnitTest/
